name: Debugging with border0
branding:
  icon: terminal

inputs:
  access-token:
    description: Border0 access token
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download border0 cli
      shell: bash
      run: |
        curl https://download.border0.com/linux_amd64/border0 -o /usr/local/bin/border0
        chmod +x /usr/local/bin/border0
        border0 version check
    - name: Print some info
      shell: bash
      run: whoami
    - name: Create and connect an ssh socket
      shell: bash
      run: |
        random_numbers=$((1000 + RANDOM % 9999))
        border0 socket create --type ssh --name gh-action-$random_numbers
        border0 socket connect gh-action-$random_numbers --sshserver
      env:
        BORDER0_ADMIN_TOKEN: ${{ inputs.access-token }}
