name: Debugging with border0
branding:
  icon: terminal
runs:
  using: composite
  steps:
    - name: Download border0 cli
      shell: bash
      run: |
        curl https://download.border0.com/linux_amd64/border0 -o /usr/local/bin/border0
        chmod +x /usr/local/bin/border0
        border0
