name: Use border0
on:
  push:
  workflow_dispatch:

jobs:
  use-border0:
    runs-on: ubuntu-latest
    steps:
      - uses: waltzofpearls/action-border0@main
        with:
          access-token: ${{ secrets.BORDER0_ADMIN_TOKEN }}
